version: '3.9'

services:
  #============================================
  # API Gateway (Punto de entrada único)
  #============================================

  #============================================
  # Microservicios de la Aplicación
  #============================================
#  auth-service:
#    build:
#      context: ./auth-service
#      dockerfile: Dockerfile
#    container_name: auth-service
#    env_file: ./.env
#    environment:
#      - PORT=3001
#      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
#      - RABBITMQ_URL=amqp://rabbitmq:5672
#    networks:
#      - app_network
#    depends_on:
#      postgres-db:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 60s
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M
#    restart: unless-stopped

#  users-service:
#    build:
#      context: ./users-service
#      dockerfile: Dockerfile
#    container_name: users-service
#    env_file: ./.env
#    environment:
#      - PORT=3002
#      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
#      - RABBITMQ_URL=amqp://rabbitmq:5672
#    networks:
#      - app_network
#    depends_on:
#      postgres-db:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 60s
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M
#    restart: unless-stopped
#
#  media-service:
#    build:
#      context: ./media-service
#      dockerfile: Dockerfile
#    container_name: media-service
#    env_file: ./.env
#    environment:
#      - PORT=3003
#      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
#      - RABBITMQ_URL=amqp://rabbitmq:5672
#    networks:
#      - app_network
#    depends_on:
#      postgres-db:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 60s
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M
#    restart: unless-stopped

  #============================================
  # Base de Datos
  #============================================
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  #============================================
  # Agente de Mensajes (Message Broker)
  #============================================
  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto para clientes AMQP
      - "15672:15672" # Puerto para la UI de management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - app_network
    environment:
      "RABBITMQ_DEFAULT_PASS": "admin"
      "RABBITMQ_DEFAULT_USER": "admin"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  #============================================
  # Stack de Logging (ELK)
  #============================================
  elasticsearch:
    image: elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false # Deshabilitado para desarrollo local
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app_network
    restart: unless-stopped

  logstash:
    image: logstash:8.14.1
    container_name: logstash
    ports:
      - "5000:5000/tcp"
    volumes:
      - ./infrastructure/logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - app_network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: kibana:8.14.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app_network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  #============================================
  # Stack de Monitoreo (Métricas)
  #============================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - app_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app_network
    depends_on:
      - prometheus
    restart: unless-stopped

#============================================
# Volúmenes y Redes
#============================================
volumes:
  postgres_data:
  rabbitmq_data:
  es_data:
  prometheus_data:
  grafana_data:

networks:
  app_network:
    driver: bridge