# ==========================================
# METRICBEAT CONFIGURATION
# metricbeat/metricbeat.yml
# ==========================================

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ==========================================
# MODULES CONFIGURATION
# ==========================================
metricbeat.modules:

  # Sistema general
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
      - entropy
      - core
      - diskio
      - socket
      - service
      - users
    enabled: true
    period: 10s
    processes: ['.*']
    cpu.metrics: ["percentages", "normalized_percentages"]
    core.metrics: ["percentages"]

  # Docker
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - event
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  # Elasticsearch
  - module: elasticsearch
    metricsets:
      - node
      - node_stats
      - cluster_stats
    period: 10s
    hosts: ["http://elasticsearch:9200"]
    enabled: true

  # RabbitMQ
  - module: rabbitmq
    metricsets:
      - node
      - queue
      - connection
      - exchange
    period: 10s
    hosts: ["http://rabbitmq:15672"]
    username: admin
    password: admin123
    enabled: true

  # Kibana
  - module: kibana
    metricsets:
      - status
      - stats
    period: 10s
    hosts: ["http://kibana:5601"]
    enabled: true

# ==========================================
# PROCESSORS
# ==========================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# ==========================================
# OUTPUT CONFIGURATION
# ==========================================
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"

# ==========================================
# KIBANA CONFIGURATION
# ==========================================
setup.kibana:
  host: "kibana:5601"

# ==========================================
# TEMPLATE CONFIGURATION
# ==========================================
setup.template:
  name: "metricbeat"
  pattern: "metricbeat-*"
  enabled: true
  settings:
    index:
      number_of_shards: 1
      number_of_replicas: 0

# ==========================================
# DASHBOARD SETUP
# ==========================================
setup.dashboards:
  enabled: true

# ==========================================
# LOGGING
# ==========================================
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644